### ISSUE TITLE
Scripts to Reproduce Synthetic R/S Results

### ISSUE THREAD

**Issue by hansen7** [PattanaikL/chiral_gnn#1]
Hi, there. Thanks for providing the code! 

It seems that `train.py` is for the tasks on the D4DCHP dataset. Would you mind providing the scripts/instructions on reproducing the toy binary classification results (i.e., Table1 and Section 6.3.3)

**Comment by PattanaikL** [comment]
Just updated the README, so you should be all set!

**Comment by hansen7** [comment]
Thanks! I guess you missed the `--gnn_type`

**Comment by PattanaikL** [comment]
yep just added some additional details :)
